### ISSUE TITLE
Custom error messages

### ISSUE THREAD

**Issue by planestepper** [Baggz/Amanda#18]
It would be useful to be able to specify custom error messages directly on the Amanda schema definition. I'd suggest accepting an object in the lines of

```
message: {
  regex: { text: "Your custom message here" }
  type: { text: "Your custom message 2 here" }
}
```

which would be parsed upon a failed validation. The property names of the message object would be the name of the Amanda validator that should consume them.

**Comment by Baggz** [comment]
Good idea! I'll look into it over the weekend

**Comment by planestepper** [comment]
Sounds great. I just created a parser for the error object in my work that provides output not nearly as clear as we can with custom messages :)

**Comment by Baggz** [comment]
Hi, sorry for the delay! Documentation is in the _[README.md](https://github.com/Baggz/Amanda/tree/dev#messages)_ file. What do you think? Will it meet your needs?

**Comment by planestepper** [comment]
No problem - I know we all have many tasks ;-) Looking great.
