### ISSUE TITLE
singleError fails with custom validators

### ISSUE THREAD

**Issue by planestepper** [Baggz/Amanda#19]
Creating a schema and then calling the validate method with added custom validators while setting `{ singleError: false }` on the method call returns no errors to the callback. Removing the `{ singleError: false }` makes it work again. It seems the issue lies not on the value provided for `singleError`, as passing `{ singleError: true }` also breaks the validation error returns. My tests have shown that, even though the error objects are not returned, the custom methods _do_ run.

**Comment by planestepper** [comment]
I've added https://github.com/Baggz/Amanda/pull/20 with the fix for the issue.

**Comment by Baggz** [comment]
Could you provide me with an example, please? I can't replicate this issue.

**Comment by planestepper** [comment]
Does a coffee test work for you?

**Comment by Baggz** [comment]
Sure.

**Comment by planestepper** [comment]
Hmm. My tests do not behave the same as my script does... so I guess the issue was between the keyboard and chair. If something else pops up I'll add it here.
