### ISSUE TITLE
Cross-field validations

### ISSUE THREAD

**Issue by planestepper** [Baggz/Amanda#22]
Me again. In a real use-case, I had to check if a field named 'name' was equal to the concatenation of the field 'identifier', a dash and of the field 'language'. Issue is these values are currently being hand-written to JSON files, so I can't enforce that in an admin interface thus far - and this has shown me the lack of support for this kind of check within amanda (I may be wrong). The solution I found was to get the current JSON-parsed object and make it available globally in a variable (ugly but functional). One other detail is that, of course, this validation runs in custom validators.

So adding this support (cross-field checks) maybe by allowing access to the object being validated would be a great plus in my opinion.

**Comment by Baggz** [comment]
Hi,

a new version of Amanda ([v0.4.0](https://github.com/Baggz/Amanda/pull/35)) has been released. All attributes have an **access to the internal API** now. So you can easily get a value of an instance, a schema or whatever you want.

Here is a brief eaxample.

``` javascript
/**
 * MyAttribute
 */
var myAttribute = function(property, propertyValue, attributeValue, propertyAttributes, callback) {

  console.log(this.instance);
  console.log(this.schema);

  this.addError();

  return callback();

};

amanda.addAttribute('myAttribute', myAttribute);
```

Is this what you wanted?

**Comment by planestepper** [comment]
Perfect!
