### ISSUE TITLE
validate option { onlyErrorCallback:true}

### ISSUE THREAD

**Issue by Tapsi** [Baggz/Amanda#33]
It was very hard to me to find out that the callback will every time called by your library. Often I only need to do some things if the validation fails, else not...

cool would be

amanda.validate( obj, schema, { onlyErrorCallback:true }, function(e){
  // do something on error case
});
// do things when validation was successful

BTW: great library :D

**Comment by Baggz** [comment]
The problem is that some validators can be _asynchronous_ (see the [addValidator](https://github.com/Baggz/Amanda/blob/master/docs/methods/addValidator.md) method). I would recommend you to do something like this.

``` javascript
amanda.validate(instance, schema, function(error) {
  if (error) {
    return onError(error);
  } else {
    return onSuccess();
  }
});
```

Is there anything else I can help you with? If not, please close this issue.

**Comment by Tapsi** [comment]
I wanted to prevent nesting functions and such things, but I use a template function now. But thanks for the fast response. :)
