### ISSUE TITLE
validates validator for amanda :P

### ISSUE THREAD

**Issue by Tapsi** [Baggz/Amanda#34]
Often I have a situation in a game, that a schema will be used by different other schemas. Like a position will be used by an unit, in a move way and so on. I know you can validate the object with more than one schema or simply write the conditions into every schema. But both for me is like an anti pattern and not update friendly... 
So I wrote a validator and want to share it with you, because I think it could be useful for the standard distribution as well.

var amanda = require('./../lib/amanda.js');

amanda.addValidator('validates',function(property, propertyValue, validator, propertyValidators, callback) {

  if( typeof validator === 'array' ){
    // if validator value is an array then try to validate all schemas
    for( var i=0,e=validator.length; i<e; i++ ) amanda.validate( propertyValue, validator[i], function(e){
      return (e)? callback(e) : callback();
    });
  }
  else{
    amanda.validate( propertyValue, validator, function(e){
      return (e)? callback(e) : callback();
    });
  }
});

var sPos = {
  type:'object',
  properties:{
    x:{ type:'number', required:true },
    y:{ type:'number', required:true }
  }
};

var positions = {
  type:'array',
  items:{
    validates:sPos
  }
};

var dPos = {
  type:'object',
  properties:{
    p1:{
      validates:sPos,
      required:true
    },
    p2:{
      validates:sPos,
      required:true
    }
  }
}

console.log("starting");

amanda.validate( { x:0,y:0 }, sPos , function(e){
  if(e) throw Error("failed");
  console.log("t1 success");
});

amanda.validate( [{ x:0,y:0 },{ x:0,y:0 },{ x:0,y:0 },{ x:0,y:0 }], positions , function(e){
  if(e) throw Error("failed");
  console.log("t2 success");
});

amanda.validate( { p1:{ x:0,y:0 }, p2:{ x:0,y:0 } }, dPos, function(e){
  if(e) throw Error("failed");
  console.log("t3 success");
});

**Comment by schloerke** [comment]
Are you trying to do multi level schema validation? 

I updated your second and third examples and added another.

``` javascript
var amanda = require('./../lib/amanda.js');

var sPos = {
  required: true,
  type:'object',
  properties:{
    x:{ type:'number', required:true },
    y:{ type:'number', required:true }
  }
};

var positionsNew = {
  type :'array',
  items: sPos
};

var dPosNew = {
  type:'object',
  properties:{
    p1:sPos,
    p2:sPos
  }
}

console.log("starting");

amanda.validate( [{ x:0,y:0 },{ x:0,y:0 },{ x:0,y:0 },{ x:0,y:0 }], positionsNew , function(e){
  if(e) throw Error("failed");
  console.log("updated t2 success");
});

amanda.validate( { p1:{ x:0,y:0 }, p2:{ x:0,y:0 } }, dPosNew, function(e){
  if(e) throw Error("failed");
  console.log("updated t3 success");
});


var threeLevelSchema = {
  type: 'object',
  properties: {
    levelOne: {
      type: 'object',
      properties: {
        levelOne: {
          type: 'array',
          items: {
            type: 'object',
            properties: sPos
          }
        }
      }
    }
  }
}

amanda.validate(
  {
    levelOne: {
      levelTwo: [
        {x: 0, y: 0},
        {x: 0, y: 0}
      ]
    }
  }, 
  threeLevelSchema,
  function(e){
    if(e) throw Error("failed");
    console.log("threeLevelSchema success");  
  }
);
```

**Comment by Tapsi** [comment]
Ah noo, how painful. Yep it's more clear.. why I didn't see it? Shame for me ...
Thanks for the tip =D

**Comment by Baggz** [comment]
Also, in version [0.4.0](https://github.com/Baggz/Amanda/pull/35) all attributes have an access to the **internal API** (via `this` keyword). You should consider one of the following methods.
- [validateItems](https://github.com/Baggz/Amanda/blob/master/src/engines/json/validateItems.js#L9)
- [validateProperties](https://github.com/Baggz/Amanda/blob/master/src/engines/json/validateProperties.js#L9)
- [validateSchema](https://github.com/Baggz/Amanda/blob/master/src/engines/json/validateSchema.js#L9)
- [validateProperty](https://github.com/Baggz/Amanda/blob/master/src/engines/json/validateProperty.js#L10)
