### ISSUE TITLE
Amanda 0.4.3 breaks validation of 'falsey' values

### ISSUE THREAD

**Issue by ndrarmstrong** [Baggz/Amanda#50]
The 0.4.3 revision of Amanda seems to break validation of schemas that support 'falsey' values.

For instance, if I had a schema with a boolean property, Amanda 0.4.2 would allow values of `true` and `false`, but would not allow a value of  `undefined` (or a non-boolean value).  In version 0.4.3, only `true` is allowed - `false` is treated as `undefined`, despite being a legal boolean value.  Indeed, the error message I get from Amanda 0.4.3 in this case is:

```
Error: The 'booleanProperty' property is required.
The 'booleanProperty' property must be a 'boolean'. The type of the property is 'undefined'.
```

Looks like the regression is in [commit 54b712d](https://github.com/Baggz/Amanda/commit/54b712dde4059fa13a9278822896c795b20e9347), to fix special characters; instead of checking whether the property is defined (which it used to), it now checks to see whether it is 'falsey':

```
-  return (previousValue && isDefined(previousValue[currentValue])) ? previousValue[currentValue] : undefined;
+  return (source[property]) ? source[property] : undefined;
```

No pull request because I'm not sure what the initial problem with special characters was, but it should be fixable with the following, or an explicit check for `undefined`, on line 9 of [src/engines/json/getProperty.js](https://github.com/Baggz/Amanda/blob/master/src/engines/json/getProperty.js):

```
return (isDefined(source[property])) ? source[property] : undefined;
```

Great project, by the way!

**Comment by Baggz** [comment]
Fixed.
